<?php
/** @var \Kishan\Assignment6\Block\Form $block */
/** @var \Magento\Framework\Escaper $escaper */
$data = $block->getUpdate();
//$data=$block->getUpdate();
?>
<form  method="POST" action="<?= $block->getSaveUrl() ?>" >
    <h3>Edit Form Details</h3>
    <div>
        <label>ID</label>
        <input name="entity_id" type="text" value="<?= $data['entity_id']?>" readonly/>
    </div>
    <div>
        <label>Enabled</label>
        <input name="enable" type="text" value="<?=  $data['enable']?>"/>
    </div>
    <div>
        <label>First Name</label>
        <input name="firstname" type="text" value="<?=  $data['firstname']?>"/>
    </div>
    <div>
        <label>Last Name</label>
        <input name="lastname" type="text" value="<?=  $data['lastname']?>" />
    </div>
    <div>
        <label>Dob</label>
        <input name="dob" type="date" value="<?=  $data['dob']?>" />
    </div>
    <div>
        <label>Mobile Number</label>
        <input name="number" type="number" value="<?=  $data['number']?>" />
    </div>
    <div>
        <label>Weight</label>
        <input name="weight" type="text" value="<?=  $data['weight']?>" />
    </div>
    <div>
        <label>Price</label>
        <input name="price" type="text" value="<?=  $data['price']?>" />
    </div>
    <button>save</button>
</form>
