<?php
/**
 *
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Unit2\HelloWorldRedirect\Controller\Adminhtml\Action;

/**
 * Class HelloWorld
 * Unit2\HelloWorldRedirect\Controller\Adminhtml\Action
 */
class HelloWorld extends \Magento\Backend\App\Action
{
    /**
     * * execute
     *
     * Execute method
     */
    public function execute()
    {
        $this->_redirect('catalog/category/edit/id/15');
    }

    /**
     * Link must be generated by server side
     *
     * It's only for education purpose!
     *
     * @return bool
     */
    public function processUrlKeys()
    {
        return true;
    }
}
